### ISSUE TITLE
Argument Serialization Error with Interaction in version 9.2.0

### ISSUE THREAD

**Issue by keyur555** [ElrondNetwork/elrond-sdk-erdjs#150]
Hello,

When I use the Interaction class with the "withSingleESDTTransfer" method to build a Transaction, then I get this error since the Version 9.2.0. The error I did not get in 9.1.0.

Uncaught (in promise) TypeError: t.isSet is not a function
    at r (app.js)
    at t.ArgSerializer.valuesToBuffers (app.js)
    at t.ArgSerializer.valuesToStrings (app.js)
    at t.ArgSerializer.valuesToString (app.js)
    at s (app.js)
    at t.ContractCallPayloadBuilder.build (app.js)
    at w.call (app.js)
    at t.Interaction.buildTransaction (app.js)

It could be a bug.

Thank you!

**Comment by keyur555** [comment]
This is another error after the upgrade to 9.2.0

Uncaught (in promise) TypeError: e.getFieldsDefinitions is not a function
    at t.TypeMapper.mapStructType (app.js)
    at t.TypeMapper.mapRecursiveType (app.js)
    at t.TypeMapper.mapType (app.js)
    at app.js
    at Array.map (<anonymous>)
    at b (app.js)
    at y.remapToKnownTypes (app.js)

**Comment by andreibancioiu** [comment]
Hello @keyur555, and thank you for reporting this :pray:  

Do you think you can post a minimal example that presents the issue?

**Comment by keyur555** [comment]
@andreibancioiu 

Yes, thank you. My code is:

let registry = await AbiRegistry.load({ urls: [url] })
let abi = new SmartContractAbi(registry, [name])
let contract = new SmartContract({ address: new Address(address), abi })
let function = new ContractFunction(functionName)
let interaction = new Interaction(contract, function, function, [])
interaction.withSingleESDTTransfer(tokenbalance)
interaction.withGasLimit(new GasLimit(gasLimit))
let transaction = interaction.buildTransaction()
transaction.send(proxy)

**Comment by andreibancioiu** [comment]
@keyur555, for the first error (`TypeError: t.isSet is not a function`) - for `OptionalValue`, if missing, the argument has to be something like:

```
new OptionalValue(new OptionalType(new SomeTypeHereAccordingToTheAbi()))
```

For the second error, it's a bit harder to figure out the root cause. Does it happen when loading the ABI, right?

**Comment by andreibancioiu** [comment]
Should now be fixed in v9.2.4 :pray:
